name: flutter_coinapi
description: Flutter CoinAPI with dio, get_it, freezed
version: 1.0.1+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  dio: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.5.0


dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  carapacik_lints: ^1.1.3
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
  json_serializable: ^6.2.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800

flutter_gen:
  output: lib/resources/
